Repository Lobby-Hoes/hobbylos-data, pull requests merged in 2022-06, with the labels that each got.

#2 split data in separate files
  README.md
  data.json
  folgen.json
  index.js
  mathefacts.json
  staedtegeschichten.json
Labels: enhancement

#3 Remove empty Mathefacts
  mathefacts.json
Labels: enhancement

#4 fixed wrong folgenname
  folgen.json
Labels: bug, good first issue

#5 Added episode 47
  folgen.json
Labels: enhancement

#8 episodes 48 and 49
  folgen.json
Labels: Update
